/**
 * Database package entry point.
 *
 * Re-exports the generated Prisma client plus the shared NestJS module and
 * service. The API (and later workers) get everything database-related from
 * here; ORM models are never re-declared in `@apteez/types`, keeping the
 * database implementation details out of API responses by construction.
 *
 * Enums are value exports (usable at runtime); models are type-only exports.
 */
export { Prisma, PrismaClient } from '@prisma/client';
export {
  AttemptStatus,
  ChallengeCompletionReason,
  ChallengeOutcome,
  ChallengeStatus,
  ContestParticipantStatus,
  ContestResultStatus,
  ContestResultVisibility,
  ContestScoringModel,
  ContestStatus,
  ContestSuspiciousEventType,
  ContributionStatus,
  Difficulty,
  DiscussionReactionType,
  DiscussionReportReason,
  DiscussionReportStatus,
  EventStatus,
  LearningAccessLevel,
  LearningContentStatus,
  LearningProgressStatus,
  PointTransactionType,
  ProblemAssetKind,
  ProblemContentMode,
  ProblemStatus,
  RatingProcessingStatus,
  RatingResult,
  RatingScope,
  SubmissionContext,
} from '@prisma/client';
export type {
  Achievement,
  AuthIdentity,
  Category,
  Challenge,
  ChallengeAnswer,
  ChallengeQuestion,
  ChallengeRating,
  ChallengeRatingHistory,
  Contest,
  ContestAnswer,
  ContestParticipant,
  ContestQuestion,
  ContestRating,
  ContestRatingHistory,
  ContestResult,
  ContestSuspiciousEvent,
  Contribution,
  DiscussionPost,
  DiscussionReaction,
  DiscussionReply,
  DiscussionReport,
  Event,
  EventParticipation,
  ExamTag,
  FavoriteCollection,
  FavoriteCollectionItem,
  LearningConcept,
  LearningLesson,
  LearningLessonExam,
  LearningLessonProblem,
  LearningPath,
  LearningTopic,
  Permission,
  PointTransaction,
  Problem,
  ProblemAsset,
  ProblemExam,
  ProblemOption,
  RatingHistory,
  Role,
  RolePermission,
  Submission,
  Subtopic,
  Topic,
  User,
  UserAchievement,
  UserRating,
  UserRole,
  UserStreak,
  UserLearningProgress,
} from '@prisma/client';
export { PrismaModule } from './prisma.module';
export { PrismaService } from './prisma.service';
